coverage:
  # https://docs.codecov.com/docs/commit-status
  status:
    patch: false
    project:
      default:
        # TODO(@avivkeller): Once our coverage > 80%,
        # increase this to 80%, and increase on increments
        target: 70%
